# 这是一个knn 的总结

# 首先进行准备（存放数据的变量的准备）：

In [1]:
import  numpy as np
import  csv


X= np.zeros((351 , 34), dtype= 'float' )
#print(X) #此时只是建立了一个数据空间，并没有值
y = np.zeros((351 ,) , dtype = "bool"  )
#上面建立了数据集的模板 并没有数据集


In [2]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


zeros : 创建一个元素全为0的矩阵，比如a=zeros(3,5);就是创建一个3行5列的0矩阵。 


In [3]:
dataset = "D:\\resu\\python_test\\打的程序\\程序\\ionosphere.data"

In [4]:
data = open("D:\\resu\\python_test\\打的程序\\程序\\ionosphere.data" , "r")
data = data.read()

In [5]:
with open(dataset ,"r") as imput_file:
    
    reder = csv.reader(imput_file)  #将文档以csv 的格式打开
    
    for i  ,row in enumerate(reder): # 将其标序号并一一枚举各个值
        
        data = [float(dataum) for dataum in row[: -1]]#(除了最后一行，其他的都要取到)
        X[i] = data
# ----------------------这句话是什么意思 — （已知样本的具体数据）
        y[i] = row[-1] == 'g' #这句话是什么意思 (获取每个个体最后一个类别表示类别的值，把字母转为数字，如果类别为g ，就是1（true）否则为0（false）
       # print("yi" , y[i])

现在已经将所有数据都保存下来了

In [6]:
from sklearn.model_selection import train_test_split

#分割数据：
x_train , x_test ,y_train ,  y_test = train_test_split(X , y , random_state = 14)

# 将数据分割，分为训练集测试集：


In [11]:
#训练数据：
from sklearn.neighbors import  KNeighborsClassifier
estimator = KNeighborsClassifier()
estimator.fit(x_train , y_train)

#评估表现：
y_predict = estimator.predict(x_test)
accuracy = np.mean(y_test == y_predict)*100
print(" the accuracy is {0:1f}%".format(accuracy))

 the accuracy is 86.363636%


In [14]:
#训练数据：
from sklearn.neighbors import  KNeighborsClassifier
estimator = KNeighborsClassifier()
estimator.fit(x_train , y_train)

#评估表现：
y_predict = estimator.predict(x_test)
accuracy = np.mean(y_test == y_predict)
print(" the accuracy is {0:1f}%".format(accuracy)*100)#为什么放在这里会有很多打印出来？  因为这个是将那个百分数打印100次，而不是将数字乘以100下面写上正确做法：

 the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accuracy is 0.863636% the accurac

In [15]:
#训练数据：
from sklearn.neighbors import  KNeighborsClassifier
estimator = KNeighborsClassifier()
estimator.fit(x_train , y_train)

#评估表现：
y_predict = estimator.predict(x_test)
accuracy = np.mean(y_test == y_predict)
print(" the accuracy is {0:1f}%".format(accuracy*100))

 the accuracy is 86.363636%


In [8]:
#交叉验证
# from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import cross_val_score
scores = cross_val_score(estimator , X , y ,scoring= "accuracy")
average_accuracy = np.mean(scores) *100
print("1111",average_accuracy)
print("the average accuracy is :{0:.1f}%".format(average_accuracy))

1111 82.61971830985915
the average accuracy is :82.6%


一般都采用交叉验证，这样更能体现准确性。

In [16]:
#后面 就是调整算法，找到最好的领近数

In [17]:
avg_scores= []
all_scores =[]
parameter_value = list(range(1 ,21 ))# 1-2之间的数；（1）


In [18]:
for n_neighbors in parameter_value :
    estimator = KNeighborsClassifier(n_neighbors =  n_neighbors) #就是临近的数由1 - 20来看准确率
    scores = cross_val_score(estimator , X, y ,scoring= "accuracy")
    avg_scores.append(np.mean(scores))#交叉验证的平均分（测试集不止一个数字） 一堆测试集，每个都有
    all_scores.append(scores) #交叉验证

In [19]:
from  matplotlib import  pylab as plt
plt.plot( parameter_value , avg_scores , "--")
plt.show()

<Figure size 640x480 with 1 Axes>

In [20]:
#将数据处理得更规范化：
x_broken = np.array(X)
#print("x_broken1 \n",x_broken[2 ,:],"\n")
x_broken[: , ::2] /=10
#print("x_broken2 \n",x_broken[2 ,:])
#这样就让奇数行比偶数行的数字要小，
#然后在来评估数据：
#创建knn 的类
estmator = KNeighborsClassifier()
#进行数据的操作：
#交叉验证得值：：
orgion_scores1 = cross_val_score(estimator , X, y ,scoring = "accuracy")
print((orgion_scores1))
print("orgion_scores {0:.1f}% :".format(np.mean(orgion_scores1)*100) )

#打乱后的：
broken_scores = cross_val_score(estimator , x_broken ,y , scoring = "accuracy")
print(broken_scores)
print("broken_scores{0:.1f}% :".format(np.mean(broken_scores)*100) )

[0.84507042 0.75714286 0.82857143 0.88571429 0.88571429]
orgion_scores 84.0% :
[0.69014085 0.67142857 0.64285714 0.67142857 0.64285714]
broken_scores66.4% :


In [21]:
#用自带的库进行标准化： (以前直接可以fit——transform 的对象是什么？）
from  sklearn.preprocessing import MinMaxScaler
x_broken_transfromed =  MinMaxScaler().fit_transform(x_broken)
#print(x_transfromed)
estimator = KNeighborsClassifier()
transfromed_scores = cross_val_score(estimator , x_broken_transfromed , y, scoring="accuracy")
print("the transfromed_scores is {0:.1f}%".format(np.mean(transfromed_scores)*100))

#更好的数据操作就是流水线：
from  sklearn.pipeline import Pipeline
#使用 MinMaxScaler 将数据统一到0-1；
#用knn 分类器
#写流水线：
scaling_pipline = Pipeline([  ('scale' , MinMaxScaler() )  , ('prdict' , KNeighborsClassifier() )])
scores = cross_val_score(scaling_pipline , x_broken , y ,scoring= "accuracy" )
print( "the scores is {0:.1f}%".format(np.mean(scores) *100))


the transfromed_scores is 82.9%
the scores is 82.9%
